# Generated by Django 5.1.1 on 2024-09-16 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=120)),
                (
                    "description",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("hours", models.FloatField(default=0)),
                ("planned_start_date", models.DateTimeField(blank=True, null=True)),
                ("planned_end_date", models.DateTimeField(blank=True, null=True)),
                ("actual_start_date", models.DateTimeField(blank=True, null=True)),
                ("actual_end_date", models.DateTimeField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("sub_tasks", models.ManyToManyField(blank=True, to="tasks.task")),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="tasks", to="tasks.tag"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
